# Generated by Django 4.1.4 on 2022-12-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название мероприятия')),
                ('type', models.IntegerField(choices=[(1, 'Хакатон'), (2, 'Лекция'), (3, 'Семинар'), (4, 'Митап')], default=2, verbose_name='Тип мероприятия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка регистрации')),
            ],
        ),
    ]
