# Generated by Django 4.1.4 on 2022-12-17 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_traffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя студента')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятия', 'verbose_name_plural': 'Мероприятии'},
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_check', models.BooleanField(default=False, verbose_name='Посетил?')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Уникальная ссылка для отзыва')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_traffic.event', verbose_name='Мероприятие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_traffic.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Регистрация на мероприятие',
                'verbose_name_plural': 'Регистрации на мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.IntegerField(verbose_name='Оценка')),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_traffic.event', verbose_name='Мероприятие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_traffic.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
